{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "83182ab1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import joblib\n",
    "\n",
    "# ==================================\n",
    "# Load artifacts\n",
    "# ==================================\n",
    "\n",
    "@st.cache_resource\n",
    "def load_artifacts():\n",
    "\n",
    "    model = tf.keras.models.load_model(\n",
    "        \"tuned_resnet_model.keras\"\n",
    "    )\n",
    "\n",
    "    preprocessor = joblib.load(\n",
    "        \"preprocessor.joblib\"\n",
    "    )\n",
    "\n",
    "    meta = joblib.load(\n",
    "        \"tuned_resnet_meta.joblib\"\n",
    "    )\n",
    "\n",
    "    return model, preprocessor, meta\n",
    "\n",
    "model, preprocessor, meta = load_artifacts()\n",
    "\n",
    "threshold = meta[\"threshold\"]\n",
    "\n",
    "# ==================================\n",
    "# Business Rule\n",
    "# ==================================\n",
    "\n",
    "def apply_own_car_rule(df):\n",
    "\n",
    "    df = df.copy()\n",
    "\n",
    "    df.loc[\n",
    "        (df[\"FLAG_OWN_CAR\"] == \"N\")\n",
    "        & (df[\"OWN_CAR_AGE\"].notnull()),\n",
    "        \"OWN_CAR_AGE\"\n",
    "    ] = 0\n",
    "\n",
    "    return df\n",
    "\n",
    "# ==================================\n",
    "# UI\n",
    "# ==================================\n",
    "\n",
    "st.title(\"Loan Default Prediction\")\n",
    "\n",
    "tab1, tab2 = st.tabs(\n",
    "    [\"Upload CSV\", \"Manual Input\"]\n",
    ")\n",
    "\n",
    "# ==================================\n",
    "# TAB 1\n",
    "# ==================================\n",
    "\n",
    "with tab1:\n",
    "\n",
    "    uploaded_file = st.file_uploader(\n",
    "        \"Upload customer data\",\n",
    "        type=[\"csv\"]\n",
    "    )\n",
    "\n",
    "    if uploaded_file:\n",
    "\n",
    "        df = pd.read_csv(uploaded_file)\n",
    "\n",
    "        st.write(df.head())\n",
    "\n",
    "        try:\n",
    "\n",
    "            df = apply_own_car_rule(df)\n",
    "\n",
    "            X = preprocessor.transform(df)\n",
    "\n",
    "            probs = model.predict(\n",
    "                X,\n",
    "                verbose=0\n",
    "            ).flatten()\n",
    "\n",
    "            preds = (\n",
    "                probs >= threshold\n",
    "            ).astype(int)\n",
    "\n",
    "            result = df.copy()\n",
    "\n",
    "            result[\"Default_Probability\"] = probs\n",
    "\n",
    "            result[\"Prediction\"] = np.where(\n",
    "                preds == 1,\n",
    "                \"Risky\",\n",
    "                \"Pays Regularly\"\n",
    "            )\n",
    "\n",
    "            st.success(\"Prediction completed\")\n",
    "\n",
    "            st.dataframe(result.head())\n",
    "\n",
    "            st.download_button(\n",
    "                \"Download Results\",\n",
    "                result.to_csv(index=False),\n",
    "                \"predictions.csv\"\n",
    "            )\n",
    "\n",
    "        except Exception as e:\n",
    "\n",
    "            st.error(str(e))"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
